### ISSUE TITLE
Broken Integration

### ISSUE THREAD

**Issue by nikolas22t** [barban-dev/homeassistant-midea-dehumidifier#23]
Hello, The last update of Home Assistant (2021.4.0) broke integration to midea dehumidifier 

[https://ibb.co/0sbNhLY](url)
[https://ibb.co/k52vWM7](url)

2021-04-08 08:53:50 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'midea_dehumidifier'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'midea_dehumidifier'

**Comment by saltabas** [comment]
Hello, the same to me upgrading HA 2021.4.0


Logger: homeassistant.setup
Source: setup.py:307
Unable to prepare setup for platform midea_dehumidifier.sensor: Platform not found (cannot import name 'ATTR_MODE' from 'homeassistant.components.humidifier.const' (/usr/src/homeassistant/homeassistant/components/humidifier/const.py)).

**Comment by sanderlv** [comment]
Here too broken

**Comment by MauricioXavier13** [comment]
Same here! 
Waiting for the update and thank for work!

**Comment by MikeLehnitz** [comment]
I have the same problem with my two dehumidifiers

**Comment by cristi2005** [comment]
same here....

**Comment by drthanwho** [comment]
That is only a warning and has been showing up since the previous release (2021.3). As the warning says this will become a breaking change as of 2021.6

The reason the integration is broken is not that. It's explained on this issue already #22

**Comment by sanderlv** [comment]
It is not only a warning. It is just not working... entities greyed out and unavailable...

**Comment by drthanwho** [comment]
As I said that log you showed is a warning. It's been showing up for a month now. a warning doesn't break an integration. 

The reason it's broken I've already explained on this issue here #21 and made a PR for it to be fixed here #22 

Until the guy who made the integration fixes this, you can check my PR and make the change to the problematic file manually.

**Comment by sanderlv** [comment]
Ok think I get you... reading that pr22 does not hive me a direct "eureka" moment...

**Comment by drthanwho** [comment]
Check "Files Changed" for what is edited and and change that in the same file in your /custom_components folder. Or replace the file completely with mine. That should fix the issue for now

**Comment by cristi2005** [comment]
i put in my humidifier.py this 2 line: 

from homeassistant.const import ATTR_ENTITY_ID, ATTR_MODE
from homeassistant.const import ATTR_MODE

restarted HA, but still not working.

**Comment by drthanwho** [comment]
> i put in my humidifier.py this 2 line:

you only need to add 
`from homeassistant.const import ATTR_MODE`

and also remove `ATTR_MODE` from further down

**Comment by cristi2005** [comment]
Oleeeee, now working perfect.
@drthanwho Thank you for help, you are the great man.
Cristi

**Comment by sanderlv** [comment]
@barban-dev is it possible to update this in your code please 🤩

**Comment by Bettinaglio** [comment]
Same here still in 2021.4.2: /config/deps/ is empty. Error is the following:

Logger: homeassistant.setup
Source: setup.py:307 
First occurred: 7:55:44 (2 occurrences) 
Last logged: 7:55:44

Unable to prepare setup for platform midea_dehumidifier.humidifier: Platform not found (cannot import name 'ATTR_MODE' from 'homeassistant.components.humidifier.const' (/usr/src/homeassistant/homeassistant/components/humidifier/const.py)).
Unable to prepare setup for platform midea_dehumidifier.sensor: Platform not found (cannot import name 'ATTR_MODE' from 'homeassistant.components.humidifier.const' (/usr/src/homeassistant/homeassistant/components/humidifier/const.py)).
Added the line:
from homeassistant.const import ATTR_MODE
and deleted line further down  "ATTR_MODE"
Thanks a lot for your hint @drthanwho. Hopefully the owner of this HACS turns back to update (and keep up and running) the integration.

**Comment by MikeLehnitz** [comment]
Thanks for fixing the bug

**Comment by nikolas22t** [comment]
Thanks Thanasi!

**Comment by barban-dev** [comment]
Fixed

**Comment by Bettinaglio** [comment]
> Fixed

Thanks a lot @barban-dev ! Grazie Andrea!

**Comment by sanderlv** [comment]
Thanks!!! Appreciated!
